---
nextcloud_parent_dir: "/home/{{ ansible_user }}/docker/nextcloud"
nextcloud_postgres_db: "nextcloud"
nextcloud_version: "34.0.3"
nas_mount_dir: /mnt/nas
nas_path: "//{{ hostvars['KVM-SRV01'].ansible_host }}/NAS"

www_data_uid: 33
www_data_gid: 33