---
# Test the host connection
- name: Host Connection Test
  hosts: all
  gather_facts: false
  tags: host_connection_test
  tasks:
    - import_role:
        name: system_information

# Hypervisor Configuration
# 1. global_configuration
# 2. hyper-v_host_configuration
# 3. vm_deployment
- name: Hypervisor Configuration
  import_playbook: playbooks/hypervisor_configuration.yml

# VM Configuration
# 1. windows_vm_configuration
# 2. linux_vm_configuration
- name: VM Configuration
  import_playbook: playbooks/vm_configuration.yml

# Domain Configuration (domain_configuration)
- name: Domain Configuration
  import_playbook: playbooks/domain_configuration.yml

# Service Configuration
# 1. iis_configuration
# 2. container_deployment
- name: Service Configuration
  import_playbook: playbooks/service_configuration.yml