---
# Test the host connection
- name: VM Connection Test
  hosts: servers:pcs:vms
  gather_facts: false
  tags: host_connection_test
  vars_files:
    - variables/windows_var.yml
  tasks:
  - name: Host Connection Test
    ansible.windows.win_powershell:
      script: |
        $osInfo = Get-CimInstance Win32_OperatingSystem | Select-Object Caption, Version, ServicePackMajorVersion, OSArchitecture

        $Ansible.Result = $osInfo
        $Ansible.Changed = $false
    register: os_info
  - debug: 
      msg: "{{ os_info }}"

# Global Configuration
- name: Global Configuration
  hosts: servers:!KVM-SRV02:pcs
  gather_facts: false
  tags: global_configuration
  vars_files:
    - variables/windows_var.yml
    - variables/domain_var.yml
  tasks:
    - import_role:
        name: hostname_configuration
    - import_role:
        name: ntp_configuration
    - import_role:
        name: region_configuration
    - import_role:
        name: system_configuration
    - import_role:
        name: local_user_configuration
    - import_role:
        name: windows_updates

# Hyper-V Host Configuration
- name: Hyper-V Host Configuration
  hosts: servers:!KVM-SRV02:pcs
  gather_facts: false
  tags: hyper-v_host_configuration
  vars_files:
    - variables/vm_var.yml
    - variables/windows_var.yml
  vars:
    hyper_v_parent_dir: "{{ srv_hyper_v_parent_dir if 'servers' in group_names else pc_hyper_v_parent_dir }}"
  tasks:
    - import_role:
        name: hyper-v_configuration

# VM Deployment
- name: VM Deployment
  # hosts: servers:!KVM-SRV02:pcs
  hosts: servers:!KVM-SRV02
  gather_facts: false
  tags: vm_deployment
  vars_files:
    - variables/vm_var.yml
    - variables/windows_var.yml
  vars:
    hyper_v_parent_dir: "{{ srv_hyper_v_parent_dir if 'servers' in group_names else pc_hyper_v_parent_dir }}"
  tasks:
    - import_role:
        name: vm_deployment

# VM Configuration
- name: VM Configuration
  hosts: vms
  gather_facts: false
  tags: vm_configuration
  vars_files:
    - variables/windows_var.yml
    - variables/domain_var.yml
  tasks:
    - import_role:
        name: firewall_configuration
    - import_role:
        name: hostname_configuration
    - import_role:
        name: ntp_configuration
    - import_role:
        name: region_configuration
    - import_role:
        name: system_configuration
    - include_role:
        name: local_user_configuration
      when: "'dcs' not in group_names"
    - import_role:
        name: windows_updates

# Domain Configuration
- name: Domain Configuration
  hosts: vms
  gather_facts: false
  tags: domain_configuration
  vars_files:
    - variables/domain_var.yml
    - variables/user_var.yml
    - variables/windows_var.yml
  tasks:
    # - include_role:
    #     name: domain_creation
    #   when: "'dcs' in group_names"
    # - import_role:
    #     name: domain_join
    - include_role:
        name: domain_user_configuration
      when: "'dcs' in group_names"

# IIS Configuration
- name: IIS Configuration
  hosts: webs
  gather_facts: false
  tags: iis_configuration
  vars_files:
    - variables/windows_var.yml
  tasks:
    - import_role:
        name: iis_deployment