name: Ansible Pipeline

on:
  workflow_dispatch:
  schedule:
    # Runs daily at 02:00 UTC
    # - 10:00 PM EDT
    # - 7:00 PM PDT
    # - 4:00 AM Hungary
    # - 9:00 AM Vietnam
    # - 12:00 PM Melbourne
    - cron: '0 2 * * *'
  push:
    branches:
      - master
    paths:
      - 'ansible/**'
  pull_request:
    branches:
      - master
    paths:
      - 'ansible/**'

jobs:
  ansible:
    name: Execute Ansible Playbooks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ansible
    env:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      # Connect to Tailscale and accept subnet routes
      # OAuth scope: api_access_tokens, auth_keys, devices:core, devices:routes:read, oauth_keys
      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}
          tags: tag:ci

      - name: Setup Python
        uses: actions/setup-python@v7

      - name: Install Ansible and Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible pyvmomi

      - name: Create Vault Password File
        run: echo "$ANSIBLE_VAULT_PASSWORD" > .vault_pass

      - name: Ansible Syntax Check
        run: ansible-playbook site.yml --syntax-check --vault-password-file .vault_pass

      - name: Execute Ansible Playbook
        if: github.ref == 'refs/heads/master' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule')
        run: ansible-playbook site.yml --vault-password-file .vault_pass

      - name: Clean up Vault Password File
        if: always()
        run: rm -f .vault_pass